package com.tolulonge.footballfixtures.domain.mapper

class AllDomainMappers(
    val dataCompetitionXToDomainCompetitionXMapper: DataCompetitionXToDomainCompetitionXMapper,
    val dataTodayFixtureToDomainTodayFixtureMapper: DataTodayFixtureToDomainTodayFixtureMapper,
    val dataCompetitionFixtureToDomainCompetitionFixtureMapper: DataCompetitionFixtureToDomainCompetitionFixtureMapper
)