package com.tolulonge.footballfixtures.presentation.mapper

class AllPresentationMappers(
    val domainTodayFixtureToPresentationTodayFixtureMapper: DomainTodayFixtureToPresentationTodayFixtureMapper,
    val domainCompetitionXToPresentationCompetitionXMapper: DomainCompetitionXToPresentationCompetitionXMapper,
)